### ISSUE TITLE
[Bug] Invalid mapping array to array

### ISSUE THREAD

**Issue by gabplch** [rekalogika/mapper#250]
Provided test case in PR #249 

*Issue is from version 1.8 at least. Will be very thankful if you fill add fix in that version as well, as soon, as there are some services, that we can't update due to some errors

**Comment by priyadi** [comment]
This problem turns out to not as simple as I thought. It requires an explicit distinction between keyed array and lists. The problem is that yours are lists, but are being detected as array. So, Mapper uses the integer keys as the basis of identity, not the values.

Currently, Mapper detects arrays or lists using heuristics. I will be removing it in favor of explicit list declaration.

Problem: `symfony/property-info` cannot distinguish integer-keyed array and lists. The function will only be available after the migration to `symfony/type-info`. In the meantime, I think I'll introduce an attribute to indicate lists.

**Comment by priyadi** [comment]
I managed to find a way to accommodate the case by doing list checking at runtime. With a caveat: you need to add `#[AllowDelete]` on the target side, or `#[AllowTargetDelete]` on the source side. Without it, mapper won't remove existing entries from the target side.
